#!/usr/bin/env perl
#
# Program to build Toronto Perl Mongers index page.

use common::sense;
use TPM::WebSite::Builder;

my $builder = TPM::WebSite::Builder->new(
    root_dir      => '..',
    run_timestamp => time,
);

$builder->run();
exit 0;

__END__

=pod

=head1 NAME

build-index - a program to build Toronto Perl Mongers' index page.

=head1 USAGE

  build-index

=head1 DESCRIPTION

This program assembles the Toronto Perl Mongers' home page out of bits and 
pieces.

=head1 REQUIRED ARGUMENTS

None

=head1 OPTIONS

=head1 DIAGNOSTICS

=head1 EXIT STATUS

0 for success, something else otherwise.

=head1 CONFIGURATION

=head1 DEPENDENCIES

=head1 INCOMPATIBILITIES

=head1 BUGS AND LIMITATIONS

=head2 Assumptions

=over 4

=item *

One event per day

=back

=head1 AUTHOR

=head1 LICENSE AND COPYRIGHT

=cut
