#!/usr/bin/env perl
#
# Program to build Toronto Perl Mongers index page

## no critic (RequireUseStrict, RequireUseWarnings)
# Modert::Perl turns on strict and warnings.

use Modern::Perl;

use Path::Class;
use File::Basename;
use Readonly;
use Data::Dumper;
use English '-no_match_vars';
use Template;
use Carp;

my $sections = get_sections('../sections');
my $template = Template->new( { RELATIVE => 1 } );

$template->process( '../templates/index.tt', { sections => $sections, } )
    || croak $template->error();

exit 0;

sub get_sections {
    my ($frag_dir) = @_;
    Readonly my $SECTION_SUFFIX => '.html';
    my @sections;

    for my $entry ( sort grep {/\Q$SECTION_SUFFIX\E\z/xms},
        dir($frag_dir)->children )
    {
        local $RS = undef;
        push @sections,
            {
            name    => basename( $entry, $SECTION_SUFFIX ),
            content => file($entry)->slurp,
            };
    }

    return \@sections;
}
